### PR TITLE
updating UI model

### PR DESCRIPTION
**Pull request by zeph01**
I have updated the UI model. But for now, what do you think? 

- Any comments or questions or suggestions please? 
- Should I name or label the arrows anything? 
- How was following the arrows for you? Did it make sense? Was it easy/confusing?
- Last time, the image was blurry. This update should not be blurry. Let me know if the image is still not clear enough to read.

We might be making more changes in our prototype and I will be updating the UI model accordingly. 

uiModel

### CODE REVIEW

**Review by kvlinden — APPROVED** [review]
Looks complete to me!

**Review by andrewJamesBaker — APPROVED** [review]
All looks good.

**Comment by kny4** [comment]
It's so clean and neat!! I 1000000000% approve

**Review by kny4 — APPROVED** [review]
It's so clean and neat! I 100000000% approve

**Comment by Bongo9911** [comment]
Are we planning on having the "Your habit" card on the home screen link to the Profile screen? Because it isn't right now afaik. Otherwise, it looks all good!

**Pull request merged**
