### PR TITLE
Added draft of deployment model

### PR DESCRIPTION
**Pull request by kny4**
I added the first draft of a deployment model. I'm not sure if it's correct or what goes into the cylinder in the dataservice block, if anyone has any ideas. Here's what is looks like:

 
Let me know what you think!

### CODE REVIEW

**Comment by kny4** [comment]
Ok, here's the update after talking with Belina:

**Review by andrewJamesBaker — APPROVED** [review]
It looks good to me. I don't know a lot about deployment models, but I don't see any glaring issues with it.

**Comment by kvlinden** [comment]
The final version looks generally good, but you should:
- Rename the DBMS (from "habit-buddy") to "PostgresSQL".
- Retain the HabitBuddy DB artifact (i.e., the little barrel in the DBMS).
- Include the stereotype annotations on the nodes ("<<client>>", "<<server>>") along with the names you already have. See the example on the class video.

**Comment by kny4** [comment]
@kvlinden Is there any <<stereotype annotation>> for node.js?

**Comment by kvlinden** [comment]
I would probably call the NodeJS node a "<<container>>".

**Comment by kny4** [comment]
I'll probably merge this tomorrow morning is this is A-OK. Anything else, @kvlinden?

**Pull request merged**
